public enum AppLanguage: String, CaseIterable, Codable, Equatable, Sendable {
    case zhCN = "zh-CN"
    case enUS = "en-US"
}

public struct LocalizationService: Equatable, Sendable {
    public let language: AppLanguage

    public init(language: AppLanguage) {
        self.language = language
    }

    public func text(_ key: String) -> String {
        Self.tables[language]?[key] ?? Self.tables[.enUS]?[key] ?? key
    }

    private static let tables: [AppLanguage: [String: String]] = [
        .enUS: [
            "app.name": "ReadyCheck",
            "action.refresh": "Refresh",
            "action.pinWidget": "Show widget",
            "action.hideWidget": "Hide widget",
            "action.resetWidgetPosition": "Reset widget",
            "action.unpinWidget": "Unpin widget",
            "action.settings": "Settings",
            "action.connect": "Connect",
            "action.connectCodex": "Connect Codex",
            "action.disconnect": "Disconnect",
            "action.completeAuthorization": "Complete",
            "action.closeWindow": "Close Window",
            "action.quit": "Quit ReadyCheck",
            "about.title": "About",
            "about.menuItem": "About ReadyCheck",
            "about.version": "Version",
            "about.safeRefresh": "Refresh reads usage data only and never sends model-generation requests.",
            "about.source": "Codex data comes from the OAuth-authenticated ChatGPT usage endpoint.",
            "about.precision": "Percentages are shown only when 5-hour and 7-day quota fields are parseable.",
            "about.copyright": "Copyright © 2026 ReadyCheck.",
            "settings.general": "General",
            "settings.account": "Account",
            "settings.preferences": "Preferences",
            "settings.language": "Language",
            "settings.refreshInterval": "Refresh interval",
            "settings.refreshHelp": "Automatic refresh starts at 1 minute. Manual refresh is always available.",
            "settings.widgetAlwaysOnTop": "Keep widget on top",
            "settings.widgetAlwaysOnTopHelp": "When enabled, the widget floats above app windows. When disabled, normal app windows can cover it; the widget remains draggable.",
            "dashboard.subtitle": "Codex quota status and refresh controls.",
            "dashboard.refreshCadence": "Auto refresh every 1 minute. No model calls.",
            "productBrief.title": "Track Codex quota at a glance",
            "productBrief.summary": "ReadyCheck helps you monitor Codex 5-hour and 7-day quota from your Mac. Refreshes read authorized usage data only, never start model requests, and keep credentials in the system Keychain.",
            "productBrief.safeRefresh": "No model quota used",
            "productBrief.keychain": "Protected by Keychain",
            "productBrief.surfaces": "Window, menu bar, widget",
            "settings.codex": "Codex",
            "settings.quota": "Quota",
            "settings.providers": "Providers",
            "settings.providersHelp": "ReadyCheck never sends model-generation requests during quota refresh.",
            "provider.mock": "Mock data",
            "provider.mock.detail": "Demo data for layout and interaction testing.",
            "provider.localCodex": "Local Codex",
            "provider.localCodex.detail": "Local records stay hidden until quota fields are verified.",
            "provider.codexOAuth": "Codex OAuth",
            "provider.codexOAuth.detail": "Reads the internal ChatGPT usage endpoint after OAuth. If the schema changes, ReadyCheck hides percentages.",
            "provider.codexOAuth.connectedDetail": "Codex is connected. ReadyCheck keeps the token in Keychain and refreshes usage data without sending model-generation requests.",
            "quota.error.oauthRequired": "Connect Codex in Settings to show quota.",
            "quota.error.endpointCalibrationRequired": "Quota endpoint is not configured.",
            "quota.error.unsafeEndpoint": "Quota endpoint failed the safety check.",
            "quota.error.tokenRefreshFailed": "Codex authorization expired. Reconnect in Settings.",
            "quota.error.accountIdUnavailable": "Codex account id is unavailable. Reconnect Codex.",
            "quota.error.parserUnavailable": "Quota response changed. Percentages are hidden.",
            "quota.error.requestFailed": "Quota refresh failed. Try again later.",
            "oauth.status.notConnected": "Not connected",
            "oauth.status.waitingForCallback": "Waiting for callback",
            "oauth.status.exchanging": "Authorizing",
            "oauth.status.connected": "Connected",
            "oauth.status.failed": "Authorization failed",
            "oauth.account.connectedAs": "Signed in as",
            "oauth.callback.placeholder": "Paste the callback URL",
            "oauth.callback.help": "ReadyCheck listens on localhost:1455. If the browser callback does not return automatically, paste the callback URL here.",
            "oauth.callback.listening": "Waiting for the browser callback on localhost:1455.",
            "oauth.callback.manualFallback": "Automatic callback is unavailable. Paste the browser callback URL below.",
            "oauth.step.openBrowser": "Open Codex OAuth in the browser.",
            "oauth.step.waitForCallback": "Authorize in the browser and return to ReadyCheck automatically.",
            "oauth.step.refreshAfterConnect": "ReadyCheck refreshes quota after the token is stored.",
            "oauth.error.missingSession": "Start the Codex connection again.",
            "oauth.error.stateMismatch": "The callback does not match this sign-in attempt. Start the connection again.",
            "oauth.error.invalidCallback": "Paste the full callback URL from the browser.",
            "oauth.error.callbackFailed": "The browser authorization was cancelled or rejected.",
            "oauth.error.tokenExchangeFailed": "Token exchange failed. Check the callback URL and try again.",
            "oauth.error.unsafeEndpoint": "OAuth endpoint failed the safety check.",
            "oauth.error.authorizationFailed": "Authorization failed. Try connecting again.",
            "refreshInterval.1m": "1 min",
            "refreshInterval.3m": "3 min",
            "refreshInterval.5m": "5 min",
            "status.available": "Available",
            "status.estimated": "Estimated",
            "status.unavailable": "Unavailable",
            "status.error": "Error",
            "status.stale": "Stale",
            "status.needsCalibration": "Needs calibration",
            "status.live": "Live",
            "status.autoUpdate": "Auto refresh",
            "status.lastUpdated": "Last updated",
            "status.notUpdatedYet": "Not refreshed yet",
            "status.refreshing": "Refreshing quota…",
            "status.safeRefresh": "Safe refresh only. No model calls.",
            "empty.quota.title": "No quota data yet",
            "empty.quota.message": "Enable a source or connect an account, then refresh manually.",
            "empty.quota.codexMessage": "Connect Codex OAuth in Settings, then paste the callback URL to authorize quota reads.",
            "empty.quota.connectedMessage": "Codex is connected. Use manual refresh or wait for the next automatic refresh.",
            "source.mock": "Mock",
            "source.local": "Local",
            "source.usageAPI": "Usage API",
            "source.costAPI": "Cost API",
            "source.oauthAPI": "OAuth API",
            "source.manual": "Manual",
            "confidence.verified": "Verified",
            "confidence.estimated": "Estimated",
            "confidence.manual": "Manual",
            "confidence.unknown": "Unknown",
            "quota.remaining": "remaining",
            "quota.resetAt": "Resets",
            "quota.window.codex.5h": "5-hour quota",
            "quota.window.codex.7d": "7-day quota",
            "quota.window.codex.primary": "Primary quota",
            "quota.window.codex.secondary": "Secondary quota",
            "quota.window.claude.monthly": "Monthly budget",
            "quota.window.openai.monthly": "Monthly spend"
        ],
        .zhCN: [
            "app.name": "ReadyCheck",
            "action.refresh": "刷新",
            "action.pinWidget": "显示 widget",
            "action.hideWidget": "隐藏 widget",
            "action.resetWidgetPosition": "重置位置",
            "action.unpinWidget": "取消固定",
            "action.settings": "设置",
            "action.connect": "连接",
            "action.connectCodex": "连接 Codex",
            "action.disconnect": "断开",
            "action.completeAuthorization": "完成授权",
            "action.closeWindow": "关闭窗口",
            "action.quit": "退出 ReadyCheck",
            "about.title": "关于",
            "about.menuItem": "关于 ReadyCheck",
            "about.version": "版本",
            "about.safeRefresh": "刷新只读取用量数据，不发送模型生成请求。",
            "about.source": "Codex 数据来自 OAuth 授权后的 ChatGPT usage 端点。",
            "about.precision": "只有 5 小时和 7 天配额字段可解析时才显示百分比。",
            "about.copyright": "Copyright © 2026 ReadyCheck.",
            "settings.general": "通用",
            "settings.account": "账号",
            "settings.preferences": "偏好设置",
            "settings.language": "语言",
            "settings.refreshInterval": "刷新间隔",
            "settings.refreshHelp": "自动刷新从 1 分钟起步，随时可以手动刷新。",
            "settings.widgetAlwaysOnTop": "置顶 widget",
            "settings.widgetAlwaysOnTopHelp": "开启后 widget 会浮在应用窗口前方；关闭后普通应用窗口可以盖住它，widget 仍可拖动。",
            "dashboard.subtitle": "Codex 配额状态与刷新控制。",
            "dashboard.refreshCadence": "默认每 1 分钟自动刷新，不调用模型。",
            "productBrief.title": "随时掌握 Codex 配额",
            "productBrief.summary": "ReadyCheck 帮你在 Mac 上查看 Codex 5 小时和 7 天配额。刷新只读取授权后的用量数据，不发起模型请求；凭据安全保存在系统 Keychain。",
            "productBrief.safeRefresh": "不消耗模型额度",
            "productBrief.keychain": "系统 Keychain 保护",
            "productBrief.surfaces": "主窗口、菜单栏、桌面 widget",
            "settings.codex": "Codex",
            "settings.quota": "额度",
            "settings.providers": "数据源",
            "settings.providersHelp": "ReadyCheck 刷新额度时不会发送模型生成请求。",
            "provider.mock": "模拟数据",
            "provider.mock.detail": "用于界面和交互测试的演示数据。",
            "provider.localCodex": "本地 Codex",
            "provider.localCodex.detail": "本地记录只有在额度字段被验证后才会显示。",
            "provider.codexOAuth": "Codex OAuth",
            "provider.codexOAuth.detail": "OAuth 后读取 ChatGPT 内部用量端点；如果结构变化，ReadyCheck 会隐藏百分比。",
            "provider.codexOAuth.connectedDetail": "Codex 已连接。ReadyCheck 将 token 保存在系统 Keychain 中，刷新只读取用量数据，不发送模型生成请求。",
            "quota.error.oauthRequired": "请先在设置里连接 Codex，连接后显示额度。",
            "quota.error.endpointCalibrationRequired": "额度端点尚未配置。",
            "quota.error.unsafeEndpoint": "额度端点没有通过安全检查。",
            "quota.error.tokenRefreshFailed": "Codex 授权已过期，请在设置里重新连接。",
            "quota.error.accountIdUnavailable": "无法获取 Codex 账号 ID，请重新连接 Codex。",
            "quota.error.parserUnavailable": "额度响应结构发生变化，已隐藏百分比。",
            "quota.error.requestFailed": "额度刷新失败，请稍后重试。",
            "oauth.status.notConnected": "未连接",
            "oauth.status.waitingForCallback": "等待回调",
            "oauth.status.exchanging": "授权中",
            "oauth.status.connected": "已连接",
            "oauth.status.failed": "授权失败",
            "oauth.account.connectedAs": "登录账号",
            "oauth.callback.placeholder": "粘贴回调 URL",
            "oauth.callback.help": "ReadyCheck 会监听 localhost:1455。如果浏览器回调没有自动返回，请把回调 URL 粘贴到这里。",
            "oauth.callback.listening": "正在等待浏览器回调 localhost:1455。",
            "oauth.callback.manualFallback": "自动回调不可用，请把浏览器回调 URL 粘贴到下方。",
            "oauth.step.openBrowser": "在浏览器打开 Codex OAuth 授权。",
            "oauth.step.waitForCallback": "在浏览器完成授权后自动回到 ReadyCheck。",
            "oauth.step.refreshAfterConnect": "Token 存入 Keychain 后会自动刷新额度。",
            "oauth.error.missingSession": "请重新开始 Codex 连接。",
            "oauth.error.stateMismatch": "回调和本次登录不匹配，请重新连接。",
            "oauth.error.invalidCallback": "请粘贴浏览器里的完整回调 URL。",
            "oauth.error.callbackFailed": "浏览器授权被取消或拒绝。",
            "oauth.error.tokenExchangeFailed": "换取 token 失败，请检查回调 URL 后重试。",
            "oauth.error.unsafeEndpoint": "OAuth 端点没有通过安全检查。",
            "oauth.error.authorizationFailed": "授权失败，请重新连接。",
            "refreshInterval.1m": "1 分钟",
            "refreshInterval.3m": "3 分钟",
            "refreshInterval.5m": "5 分钟",
            "status.available": "可用",
            "status.estimated": "估算",
            "status.unavailable": "不可用",
            "status.error": "错误",
            "status.stale": "已过期",
            "status.needsCalibration": "需要校准",
            "status.live": "实时",
            "status.autoUpdate": "自动刷新",
            "status.lastUpdated": "上次刷新",
            "status.notUpdatedYet": "尚未刷新",
            "status.refreshing": "正在刷新额度…",
            "status.safeRefresh": "只做安全刷新，不调用模型。",
            "empty.quota.title": "暂无额度数据",
            "empty.quota.message": "启用数据源或连接账号后，手动刷新即可显示。",
            "empty.quota.codexMessage": "请先在设置里连接 Codex OAuth，并粘贴回调 URL 完成授权。",
            "empty.quota.connectedMessage": "Codex 已连接，可以手动刷新或等待下一次自动刷新。",
            "source.mock": "模拟",
            "source.local": "本地",
            "source.usageAPI": "用量 API",
            "source.costAPI": "费用 API",
            "source.oauthAPI": "OAuth API",
            "source.manual": "手动",
            "confidence.verified": "已验证",
            "confidence.estimated": "估算",
            "confidence.manual": "手动",
            "confidence.unknown": "未知",
            "quota.remaining": "剩余",
            "quota.resetAt": "重置",
            "quota.window.codex.5h": "5 小时配额",
            "quota.window.codex.7d": "7 天配额",
            "quota.window.codex.primary": "主要配额",
            "quota.window.codex.secondary": "次要配额",
            "quota.window.claude.monthly": "月度预算",
            "quota.window.openai.monthly": "月度花费"
        ]
    ]
}
