public enum AppLanguage: String, CaseIterable, Codable, Equatable, Sendable {
    case zhCN = "zh-CN"
    case enUS = "en-US"
}

public struct LocalizationService: Equatable, Sendable {
    public let language: AppLanguage

    public init(language: AppLanguage) {
        self.language = language
    }

    public func text(_ key: String) -> String {
        Self.tables[language]?[key] ?? Self.tables[.enUS]?[key] ?? key
    }

    private static let tables: [AppLanguage: [String: String]] = [
        .enUS: [
            "app.name": "ReadyCheck",
            "action.refresh": "Refresh",
            "action.pinWidget": "Show widget",
            "action.hideWidget": "Hide widget",
            "action.resetWidgetPosition": "Reset widget",
            "action.unpinWidget": "Unpin widget",
            "action.settings": "Settings",
            "action.connect": "Connect",
            "action.connectCodex": "Connect Codex",
            "action.disconnect": "Disconnect",
            "action.completeAuthorization": "Complete",
            "action.cancelAuthorization": "Cancel authorization",
            "action.retryAuthorization": "Retry authorization",
            "action.tryAgain": "Try again",
            "action.reconnect": "Sign in again",
            "action.remindLater": "Later",
            "action.closeWindow": "Close Window",
            "action.quit": "Quit ReadyCheck",
            "action.checkForUpdates": "Check for updates",
            "action.viewUpdate": "View update",
            "action.downloadUpdate": "Download update",
            "about.title": "About",
            "about.menuItem": "About ReadyCheck",
            "about.version": "Version",
            "about.safeRefresh": "Refresh reads usage data only and never sends model-generation requests.",
            "about.source": "Codex data comes from the OAuth-authenticated ChatGPT usage endpoint.",
            "about.precision": "Percentages are shown only for quota windows that Codex returns and ReadyCheck can validate.",
            "about.copyright": "Copyright © 2026 ReadyCheck.",
            "settings.general": "General",
            "settings.account": "Account",
            "settings.preferences": "Preferences",
            "settings.language": "Language",
            "settings.refresh": "Refresh",
            "settings.refreshInterval": "Refresh interval",
            "settings.refreshHelp": "Automatic refresh starts at 1 minute. Manual refresh is always available.",
            "settings.updates": "Updates",
            "settings.widget": "Widget",
            "settings.widgetStyle": "Widget style",
            "settings.widgetAlwaysOnTop": "Keep widget on top",
            "settings.widgetAlwaysOnTopHelp": "When enabled, the widget floats above app windows. When disabled, normal app windows can cover it; the widget remains draggable.",
            "settings.notchStatus": "Notch status",
            "settings.notchStatusHelp": "Show the current Codex quota below the built-in display notch.",
            "settings.notchStatusUnavailable": "Available on Mac displays with a notch.",
            "notification.resetExpiry.title": "Reset credit expires soon",
            "notification.resetExpiry.body": "Reset %d expires within %d hours: %@",
            "notification.creditsStarted.title": "Codex Credits are now in use",
            "notification.creditsStarted.body": "Your Codex quota is exhausted. Current usage is now consuming Credits.",
            "notification.history.title": "Notification history",
            "notification.history.subtitle": "Local delivery records for quota and Credit alerts.",
            "notification.history.local": "On this device",
            "notification.history.viewAll": "View all",
            "notification.history.close": "Close",
            "notification.history.emptyTitle": "No notification records yet",
            "notification.history.emptyMessage": "Future reminder attempts will appear here with their delivery result.",
            "notification.history.resetTitle": "Reset %d · %d-hour alert",
            "notification.history.legacyResetTitle": "Reset credit · %d-hour alert",
            "notification.history.creditsTitle": "Codex Credits started",
            "notification.history.expires": "Expires %@",
            "notification.history.delivered": "Sent to system",
            "notification.history.failed": "Delivery failed",
            "notification.history.legacyUnknown": "Legacy status unknown",
            "notification.history.attempts": "%d attempts",
            "notification.history.disclaimer": "“Sent to system” means the operating system accepted the notification; banner visibility still follows system notification settings.",
            "notch.openMainWindow": "Open ReadyCheck",
            "widgetStyle.minimal": "Minimal",
            "widgetStyle.detailed": "Detailed",
            "dashboard.subtitle": "Codex quota status and refresh controls.",
            "dashboard.refreshCadence": "Auto refresh every 1 minute. No model calls.",
            "productBrief.title": "Track Codex quota at a glance",
            "productBrief.summary": "ReadyCheck helps you monitor the Codex quota windows returned for your account. Refreshes read authorized usage data only, never start model requests, and keep credentials in the system Keychain.",
            "productBrief.safeRefresh": "No model quota used",
            "productBrief.keychain": "Protected by Keychain",
            "productBrief.surfaces": "Window, menu bar, widget",
            "settings.codex": "Codex",
            "settings.quota": "Quota",
            "usage.title": "Recent quota consumption",
            "usage.localRecord": "Local history",
            "usage.subtitle": "Bars show detected quota decreases for each period, measured in percentage points.",
            "usage.range": "History range",
            "usage.range.day": "24 hours",
            "usage.range.week": "7 days",
            "usage.range.month": "30 days",
            "usage.range.quarter": "90 days",
            "usage.tokenTitle": "Recent token usage",
            "usage.officialRecord": "Official Codex data",
            "usage.tokenSubtitle": "Daily token activity reported by Codex for this account.",
            "usage.lifetimeTokens": "Lifetime tokens",
            "usage.peakDailyTokens": "Peak day",
            "usage.currentStreak": "Current streak",
            "usage.daysFormat": "%lld days",
            "usage.dailyTokens": "Tokens by day",
            "usage.date": "Date",
            "usage.tokens": "Tokens",
            "usage.tokenEmptyTitle": "Token activity is unavailable",
            "usage.tokenEmptyMessage": "Codex returned account totals without daily buckets.",
            "usage.tokenHelp": "Token activity comes from the local Codex app-server. Reading it does not send a model request.",
            "usage.emptyTitle": "Collecting usage history",
            "usage.emptyMessage": "Complete two successful refreshes to show detected quota consumption.",
            "usage.lastRecorded": "Last recorded",
            "usage.time": "Time",
            "usage.remainingPercent": "Remaining quota",
            "usage.currentRemaining": "Remaining",
            "usage.consumedPercent": "Consumed points",
            "usage.barTitle": "Consumption by period",
            "usage.selectWindow": "Select quota window",
            "usage.noConsumption": "No quota decrease was detected in this range.",
            "usage.zeroExplanation": "A current balance of 0% does not mean zero usage. Zero bars mean no new quota decrease was detected in those periods.",
            "usage.collecting": "Collecting",
            "usage.consumedFormat": "Used %.0f pts",
            "usage.help": "Shows locally recorded quota decreases, not token counts. Resets, recoveries, and long data gaps are not counted as usage.",
            "settings.providers": "Providers",
            "settings.providersHelp": "ReadyCheck never sends model-generation requests during quota refresh.",
            "provider.mock": "Mock data",
            "provider.mock.detail": "Demo data for layout and interaction testing.",
            "provider.localCodex": "Local Codex",
            "provider.localCodex.detail": "Local records stay hidden until quota fields are verified.",
            "provider.codexOAuth": "Codex OAuth",
            "provider.codexOAuth.detail": "Prefers the official local Codex interface and falls back to the read-only ChatGPT usage endpoint when needed.",
            "provider.codexOAuth.connectedDetail": "Codex is connected. ReadyCheck keeps the token in Keychain and refreshes usage data without sending model-generation requests.",
            "quota.error.oauthRequired": "Connect Codex in Settings to show quota.",
            "quota.error.endpointCalibrationRequired": "Quota endpoint is not configured.",
            "quota.error.unsafeEndpoint": "Quota endpoint failed the safety check.",
            "quota.error.tokenRefreshFailed": "Codex authorization expired. Reconnect in Settings.",
            "quota.error.accountIdUnavailable": "Codex account id is unavailable. Reconnect Codex.",
            "quota.error.authorizationRejected": "Codex authorization was rejected. Sign in again.",
            "quota.error.parserUnavailable": "Quota response changed. Percentages are hidden.",
            "quota.error.requestFailed": "Quota refresh failed. Try again later.",
            "oauth.status.notConnected": "Not connected",
            "oauth.status.waitingForCallback": "Waiting for callback",
            "oauth.status.exchanging": "Authorizing",
            "oauth.status.connected": "Connected",
            "oauth.status.credentialStorageFailed": "Credential save failed",
            "oauth.status.failed": "Authorization failed",
            "oauth.account.connectedAs": "Signed in as",
            "oauth.callback.placeholder": "Paste the callback URL",
            "oauth.callback.help": "ReadyCheck listens on localhost:1455. If the browser callback does not return automatically, paste the callback URL here.",
            "oauth.callback.starting": "Starting the secure local callback on localhost:1455…",
            "oauth.callback.listening": "Waiting for the browser callback on localhost:1455.",
            "oauth.callback.manualFallback": "Automatic callback is unavailable. Paste the browser callback URL below.",
            "oauth.step.openBrowser": "Open Codex OAuth in the browser.",
            "oauth.step.waitForCallback": "Authorize in the browser and return to ReadyCheck automatically.",
            "oauth.step.refreshAfterConnect": "ReadyCheck refreshes quota after the token is stored.",
            "oauth.error.missingSession": "Start the Codex connection again.",
            "oauth.error.stateMismatch": "The callback does not match this sign-in attempt. Start the connection again.",
            "oauth.error.invalidCallback": "Paste the full callback URL from the browser.",
            "oauth.error.callbackFailed": "The browser authorization was cancelled or rejected.",
            "oauth.error.callbackFailedDetail": "Authorization failed: %@",
            "oauth.error.tokenExchangeFailed": "Token exchange failed. Check the callback URL and try again.",
            "oauth.error.tokenExchangeFailedStatus": "Token exchange failed (HTTP %d). Try again.",
            "oauth.error.tokenExchangeFailedDetail": "Token exchange failed (HTTP %d): %@",
            "oauth.error.invalidTokenResponse": "OpenAI returned an invalid token response. Try again or check for a ReadyCheck update.",
            "oauth.error.credentialStorageFailed": "Authorization succeeded, but ReadyCheck could not save the credential in Keychain.",
            "oauth.error.credentialStorageFailedStatus": "Authorization succeeded, but Keychain could not save the credential (error %d).",
            "oauth.error.keychainUnavailable": "Authorization succeeded, but the login Keychain is unavailable. Unlock it in Keychain Access, then try again.",
            "oauth.error.network": "ReadyCheck could not reach OpenAI. Check your network and try again.",
            "oauth.error.unsafeEndpoint": "OAuth endpoint failed the safety check.",
            "oauth.error.authorizationFailed": "Authorization failed. Try connecting again.",
            "refreshInterval.1m": "1 min",
            "refreshInterval.3m": "3 min",
            "refreshInterval.5m": "5 min",
            "status.available": "Available",
            "status.estimated": "Estimated",
            "status.unavailable": "Unavailable",
            "status.error": "Error",
            "status.stale": "Stale",
            "status.needsCalibration": "Needs calibration",
            "status.live": "Live",
            "status.autoUpdate": "Auto refresh",
            "status.lastUpdated": "Last updated",
            "status.notUpdatedYet": "Not refreshed yet",
            "status.refreshing": "Refreshing quota…",
            "status.safeRefresh": "Safe refresh only. No model calls.",
            "update.checking": "Checking for updates…",
            "update.available": "New version available",
            "update.bannerMessage": "Download from GitHub Releases when you are ready.",
            "update.upToDate": "ReadyCheck is up to date.",
            "update.failed": "Update check failed. Try again later.",
            "empty.quota.title": "No quota data yet",
            "empty.quota.message": "Enable a source or connect an account, then refresh manually.",
            "empty.quota.codexMessage": "Connect Codex OAuth in Settings, then paste the callback URL to authorize quota reads.",
            "empty.quota.connectedMessage": "Codex is connected. Use manual refresh or wait for the next automatic refresh.",
            "source.mock": "Mock",
            "source.local": "Local",
            "source.usageAPI": "Usage API",
            "source.costAPI": "Cost API",
            "source.oauthAPI": "OAuth API",
            "source.appServer": "Codex official interface",
            "source.manual": "Manual",
            "confidence.verified": "Verified",
            "confidence.estimated": "Estimated",
            "confidence.manual": "Manual",
            "confidence.unknown": "Unknown",
            "quota.remaining": "remaining",
            "quota.lowQuotaWarning": "Low quota",
            "quota.criticalQuotaWarning": "Very low quota",
            "quota.exhaustedWarning": "Quota exhausted. Waiting for reset",
            "quota.resetAt": "Resets",
            "quota.account": "Account",
            "quota.plan": "Plan",
            "quota.subscriptionRenewal": "Renewal",
            "quota.manualResetCount": "Manual resets",
            "quota.manualResetExpires": "Manual reset expiration (GMT+8)",
            "quota.codexCredits": "Codex Credits",
            "quota.creditsUnlimited": "Unlimited",
            "quota.manualResetIndex": "Reset",
            "quota.manualResetTimes": "time",
            "quota.notProvided": "Not provided",
            "quota.manualResetUnavailable": "Temporarily unavailable",
            "quota.manualResetNone": "No reset credits available",
            "quota.manualResetExpirationUnavailable": "expiration temporarily unavailable",
            "quota.dataSource": "Source",
            "quota.refreshedAt": "Refreshed",
            "quota.validUntil": "Valid until",
            "quota.window.codex.5h": "5-hour quota",
            "quota.window.codex.7d": "7-day quota",
            "quota.window.codex.primary": "Primary quota",
            "quota.window.codex.secondary": "Secondary quota",
            "quota.currentSevenDayUnavailable": "The current Codex quota window is temporarily unavailable.",
            "quota.window.claude.monthly": "Monthly budget",
            "quota.window.openai.monthly": "Monthly spend"
        ],
        .zhCN: [
            "app.name": "ReadyCheck",
            "action.refresh": "刷新",
            "action.pinWidget": "显示 widget",
            "action.hideWidget": "隐藏 widget",
            "action.resetWidgetPosition": "重置位置",
            "action.unpinWidget": "取消固定",
            "action.settings": "设置",
            "action.connect": "连接",
            "action.connectCodex": "连接 Codex",
            "action.disconnect": "断开",
            "action.completeAuthorization": "完成授权",
            "action.cancelAuthorization": "取消授权",
            "action.retryAuthorization": "重新授权",
            "action.tryAgain": "重新尝试",
            "action.reconnect": "重新登录",
            "action.remindLater": "稍后提醒",
            "action.closeWindow": "关闭窗口",
            "action.quit": "退出 ReadyCheck",
            "action.checkForUpdates": "检查更新",
            "action.viewUpdate": "查看更新",
            "action.downloadUpdate": "下载更新",
            "about.title": "关于",
            "about.menuItem": "关于 ReadyCheck",
            "about.version": "版本",
            "about.safeRefresh": "刷新只读取用量数据，不发送模型生成请求。",
            "about.source": "Codex 数据来自 OAuth 授权后的 ChatGPT usage 端点。",
            "about.precision": "仅对 Codex 实际返回且 ReadyCheck 可以验证的额度窗口显示百分比。",
            "about.copyright": "Copyright © 2026 ReadyCheck.",
            "settings.general": "通用",
            "settings.account": "账号",
            "settings.preferences": "偏好设置",
            "settings.language": "语言",
            "settings.refresh": "刷新",
            "settings.refreshInterval": "刷新间隔",
            "settings.refreshHelp": "自动刷新从 1 分钟起步，随时可以手动刷新。",
            "settings.updates": "软件更新",
            "settings.widget": "Widget",
            "settings.widgetStyle": "Widget 样式",
            "settings.widgetAlwaysOnTop": "置顶 widget",
            "settings.widgetAlwaysOnTopHelp": "开启后 widget 会浮在应用窗口前方；关闭后普通应用窗口可以盖住它，widget 仍可拖动。",
            "settings.notchStatus": "刘海状态",
            "settings.notchStatusHelp": "在内置屏幕刘海下方显示当前 Codex 配额。",
            "settings.notchStatusUnavailable": "仅支持带刘海的 Mac 内置屏幕。",
            "notification.resetExpiry.title": "重置卡即将到期",
            "notification.resetExpiry.body": "第 %d 次重置额度将在 %d 小时内到期：%@",
            "notification.creditsStarted.title": "已开始使用 Codex Credits",
            "notification.creditsStarted.body": "Codex 额度已用尽，当前使用已开始消耗 Credits。",
            "notification.history.title": "通知记录",
            "notification.history.subtitle": "记录本机额度与 Credits 提醒的投递结果。",
            "notification.history.local": "本机记录",
            "notification.history.viewAll": "查看全部",
            "notification.history.close": "关闭",
            "notification.history.emptyTitle": "暂无通知记录",
            "notification.history.emptyMessage": "后续提醒会在这里显示尝试时间和投递结果。",
            "notification.history.resetTitle": "第 %d 次重置 · 提前 %d 小时",
            "notification.history.legacyResetTitle": "主动重置 · 提前 %d 小时",
            "notification.history.creditsTitle": "已开始使用 Codex Credits",
            "notification.history.expires": "到期时间 %@",
            "notification.history.delivered": "已交给系统",
            "notification.history.failed": "投递失败",
            "notification.history.legacyUnknown": "旧版状态不可确认",
            "notification.history.attempts": "尝试 %d 次",
            "notification.history.disclaimer": "“已交给系统”表示操作系统已接收通知；横幅是否可见仍取决于系统通知设置。",
            "notch.openMainWindow": "打开 ReadyCheck",
            "widgetStyle.minimal": "极简",
            "widgetStyle.detailed": "详细",
            "dashboard.subtitle": "Codex 配额状态与刷新控制。",
            "dashboard.refreshCadence": "默认每 1 分钟自动刷新，不调用模型。",
            "productBrief.title": "随时掌握 Codex 配额",
            "productBrief.summary": "ReadyCheck 帮你在 Mac 上查看当前账号实际返回的 Codex 配额窗口。刷新只读取授权后的用量数据，不发起模型请求；凭据安全保存在系统 Keychain。",
            "productBrief.safeRefresh": "不消耗模型额度",
            "productBrief.keychain": "系统 Keychain 保护",
            "productBrief.surfaces": "主窗口、菜单栏、桌面 widget",
            "settings.codex": "Codex",
            "settings.quota": "额度",
            "usage.title": "近期额度消耗",
            "usage.localRecord": "本地记录",
            "usage.subtitle": "柱形表示每个时段检测到的额度下降，单位为百分点。",
            "usage.range": "历史范围",
            "usage.range.day": "24 小时",
            "usage.range.week": "7 天",
            "usage.range.month": "30 天",
            "usage.range.quarter": "90 天",
            "usage.tokenTitle": "近期 Token 使用量",
            "usage.officialRecord": "Codex 官方数据",
            "usage.tokenSubtitle": "按天展示 Codex 为当前账号返回的 Token 活动。",
            "usage.lifetimeTokens": "累计 Token",
            "usage.peakDailyTokens": "单日峰值",
            "usage.currentStreak": "连续使用",
            "usage.daysFormat": "%lld 天",
            "usage.dailyTokens": "每日 Token",
            "usage.date": "日期",
            "usage.tokens": "Token",
            "usage.tokenEmptyTitle": "暂无 Token 活动明细",
            "usage.tokenEmptyMessage": "Codex 返回了账户汇总，但没有返回每日数据。",
            "usage.tokenHelp": "Token 活动来自本机 Codex app-server，读取过程不会发送模型请求。",
            "usage.emptyTitle": "正在积累使用记录",
            "usage.emptyMessage": "完成两次成功刷新后，这里会展示检测到的额度消耗。",
            "usage.lastRecorded": "最后记录",
            "usage.time": "时间",
            "usage.remainingPercent": "剩余额度",
            "usage.currentRemaining": "当前剩余",
            "usage.consumedPercent": "消耗百分点",
            "usage.barTitle": "每时段消耗",
            "usage.selectWindow": "选择额度窗口",
            "usage.noConsumption": "该时间范围内未检测到额度下降。",
            "usage.zeroExplanation": "当前剩余 0% 不代表使用量为 0；零柱表示该时段未检测到新的额度下降。",
            "usage.collecting": "记录中",
            "usage.consumedFormat": "消耗 %.0f 个百分点",
            "usage.help": "这里展示本地成功刷新之间的额度下降，不代表 Token 数量；额度重置、恢复和长时间无数据不会计入消耗。",
            "settings.providers": "数据源",
            "settings.providersHelp": "ReadyCheck 刷新额度时不会发送模型生成请求。",
            "provider.mock": "模拟数据",
            "provider.mock.detail": "用于界面和交互测试的演示数据。",
            "provider.localCodex": "本地 Codex",
            "provider.localCodex.detail": "本地记录只有在额度字段被验证后才会显示。",
            "provider.codexOAuth": "Codex OAuth",
            "provider.codexOAuth.detail": "优先读取本机 Codex 官方接口，必要时回退到只读 ChatGPT 用量端点。",
            "provider.codexOAuth.connectedDetail": "Codex 已连接。ReadyCheck 将 token 保存在系统 Keychain 中，刷新只读取用量数据，不发送模型生成请求。",
            "quota.error.oauthRequired": "请先在设置里连接 Codex，连接后显示额度。",
            "quota.error.endpointCalibrationRequired": "额度端点尚未配置。",
            "quota.error.unsafeEndpoint": "额度端点没有通过安全检查。",
            "quota.error.tokenRefreshFailed": "Codex 授权已过期，请在设置里重新连接。",
            "quota.error.accountIdUnavailable": "无法获取 Codex 账号 ID，请重新连接 Codex。",
            "quota.error.authorizationRejected": "Codex 授权已失效，请重新登录。",
            "quota.error.parserUnavailable": "额度响应结构发生变化，已隐藏百分比。",
            "quota.error.requestFailed": "额度刷新失败，请稍后重试。",
            "oauth.status.notConnected": "未连接",
            "oauth.status.waitingForCallback": "等待回调",
            "oauth.status.exchanging": "授权中",
            "oauth.status.connected": "已连接",
            "oauth.status.credentialStorageFailed": "凭据保存失败",
            "oauth.status.failed": "授权失败",
            "oauth.account.connectedAs": "登录账号",
            "oauth.callback.placeholder": "粘贴回调 URL",
            "oauth.callback.help": "ReadyCheck 会监听 localhost:1455。如果浏览器回调没有自动返回，请把回调 URL 粘贴到这里。",
            "oauth.callback.starting": "正在启动 localhost:1455 安全回调…",
            "oauth.callback.listening": "正在等待浏览器回调 localhost:1455。",
            "oauth.callback.manualFallback": "自动回调不可用，请把浏览器回调 URL 粘贴到下方。",
            "oauth.step.openBrowser": "在浏览器打开 Codex OAuth 授权。",
            "oauth.step.waitForCallback": "在浏览器完成授权后自动回到 ReadyCheck。",
            "oauth.step.refreshAfterConnect": "Token 存入 Keychain 后会自动刷新额度。",
            "oauth.error.missingSession": "请重新开始 Codex 连接。",
            "oauth.error.stateMismatch": "回调和本次登录不匹配，请重新连接。",
            "oauth.error.invalidCallback": "请粘贴浏览器里的完整回调 URL。",
            "oauth.error.callbackFailed": "浏览器授权被取消或拒绝。",
            "oauth.error.callbackFailedDetail": "授权失败：%@",
            "oauth.error.tokenExchangeFailed": "换取 token 失败，请检查回调 URL 后重试。",
            "oauth.error.tokenExchangeFailedStatus": "换取 token 失败（HTTP %d），请重试。",
            "oauth.error.tokenExchangeFailedDetail": "换取 token 失败（HTTP %d）：%@",
            "oauth.error.invalidTokenResponse": "OpenAI 返回的 token 数据无效，请重试或检查 ReadyCheck 更新。",
            "oauth.error.credentialStorageFailed": "授权已完成，但 ReadyCheck 无法将凭据保存到 Keychain。",
            "oauth.error.credentialStorageFailedStatus": "授权已完成，但 Keychain 无法保存凭据（错误 %d）。",
            "oauth.error.keychainUnavailable": "授权已完成，但登录钥匙串当前不可用。请在“钥匙串访问”中解锁“登录”，然后重试。",
            "oauth.error.network": "ReadyCheck 无法连接 OpenAI，请检查网络后重试。",
            "oauth.error.unsafeEndpoint": "OAuth 端点没有通过安全检查。",
            "oauth.error.authorizationFailed": "授权失败，请重新连接。",
            "refreshInterval.1m": "1 分钟",
            "refreshInterval.3m": "3 分钟",
            "refreshInterval.5m": "5 分钟",
            "status.available": "可用",
            "status.estimated": "估算",
            "status.unavailable": "不可用",
            "status.error": "错误",
            "status.stale": "已过期",
            "status.needsCalibration": "需要校准",
            "status.live": "实时",
            "status.autoUpdate": "自动刷新",
            "status.lastUpdated": "上次刷新",
            "status.notUpdatedYet": "尚未刷新",
            "status.refreshing": "正在刷新额度…",
            "status.safeRefresh": "只做安全刷新，不调用模型。",
            "update.checking": "正在检查更新…",
            "update.available": "发现新版本",
            "update.bannerMessage": "准备好后可从 GitHub Releases 下载更新。",
            "update.upToDate": "ReadyCheck 已是最新版本。",
            "update.failed": "检查更新失败，请稍后重试。",
            "empty.quota.title": "暂无额度数据",
            "empty.quota.message": "启用数据源或连接账号后，手动刷新即可显示。",
            "empty.quota.codexMessage": "请先在设置里连接 Codex OAuth，并粘贴回调 URL 完成授权。",
            "empty.quota.connectedMessage": "Codex 已连接，可以手动刷新或等待下一次自动刷新。",
            "source.mock": "模拟",
            "source.local": "本地",
            "source.usageAPI": "用量 API",
            "source.costAPI": "费用 API",
            "source.oauthAPI": "OAuth API",
            "source.appServer": "Codex 官方接口",
            "source.manual": "手动",
            "confidence.verified": "已验证",
            "confidence.estimated": "估算",
            "confidence.manual": "手动",
            "confidence.unknown": "未知",
            "quota.remaining": "剩余",
            "quota.lowQuotaWarning": "额度偏低",
            "quota.criticalQuotaWarning": "额度很低",
            "quota.exhaustedWarning": "额度用尽，等待重置",
            "quota.resetAt": "重置",
            "quota.account": "账号",
            "quota.plan": "套餐",
            "quota.subscriptionRenewal": "续期时间",
            "quota.manualResetCount": "主动重置次数",
            "quota.manualResetExpires": "主动重置过期时间（GMT+8）",
            "quota.codexCredits": "Codex Credits",
            "quota.creditsUnlimited": "无限",
            "quota.manualResetIndex": "第",
            "quota.manualResetTimes": "次",
            "quota.notProvided": "未提供",
            "quota.manualResetUnavailable": "暂时无法读取",
            "quota.manualResetNone": "暂无可用主动重置",
            "quota.manualResetExpirationUnavailable": "过期时间暂不可用",
            "quota.dataSource": "来源",
            "quota.refreshedAt": "刷新时间",
            "quota.validUntil": "有效期",
            "quota.window.codex.5h": "5 小时配额",
            "quota.window.codex.7d": "7 天配额",
            "quota.window.codex.primary": "主要配额",
            "quota.window.codex.secondary": "次要配额",
            "quota.currentSevenDayUnavailable": "当前 Codex 额度窗口暂不可用。",
            "quota.window.claude.monthly": "月度预算",
            "quota.window.openai.monthly": "月度花费"
        ]
    ]
}
