import React from 'react';
import {AbsoluteFill, Easing, Img, interpolate, staticFile, useCurrentFrame} from 'remotion';

export const font = 'PingFang SC, Noto Sans CJK SC, sans-serif';
const asset = (name: string) => staticFile(`images/xhs-0130/${name}.png`);
export const Badge: React.FC = () => <div style={{display:'flex',alignItems:'center',gap:18,fontSize:34,color:'#b6c1d2'}}><Img src={asset('app-icon')} style={{width:72,height:72}}/>ReadyCheck<span style={{marginLeft:20,color:'#78c8ff'}}>Mac 开源工具</span></div>;
export const Backdrop: React.FC<{children?:React.ReactNode}> = ({children}) => <AbsoluteFill style={{background:'radial-gradient(ellipse at 90% 38%, #13355a 0%, #101b2a 40%, #080d15 80%)',color:'#f6f8ff',fontFamily:font}}><div style={{position:'absolute',top:146,left:90}}><Badge/></div>{children}</AbsoluteFill>;
const Title:React.FC<{children:React.ReactNode;sub?:string}> = ({children,sub}) => <div style={{position:'absolute',left:96,top:325,width:870}}><div style={{fontSize:88,fontWeight:700,lineHeight:1.2,letterSpacing:-3}}>{children}</div>{sub&&<div style={{fontSize:40,color:'#b5c7dd',marginTop:26,lineHeight:1.5}}>{sub}</div>}</div>;
const Reveal:React.FC<{children:React.ReactNode;style?:React.CSSProperties}> = ({children,style}) => {const f=useCurrentFrame();const t=interpolate(f,[0,18],[0,1],{extrapolateRight:'clamp',easing:Easing.out(Easing.cubic)});return <div style={{...style,opacity:t,transform:`translateY(${(1-t)*28}px)`}}>{children}</div>};
const NativeImage:React.FC<{name:string;style:React.CSSProperties}> = ({name,style}) => <Img src={asset(name)} style={{objectFit:'contain',...style}}/>;
export const DemoLabel:React.FC = () => <div style={{position:'absolute',top:1465,width:'100%',textAlign:'center',fontSize:28,color:'#93a7c0'}}>当前版本界面演示 · 配额为演示数据</div>;

export const PainScene:React.FC = () => <Backdrop><Title sub="思路还在，额度先见底。">写到一半，<br/>Codex 没额度了？</Title><Reveal style={{position:'absolute',left:170,top:690,width:720,display:'flex',alignItems:'center',gap:88}}><NativeImage name="edge" style={{width:290,height:620}}/><div><div style={{color:'#ff555f',fontSize:104,fontWeight:700}}>13%</div><div style={{fontSize:40,color:'#aebbd0',lineHeight:1.6}}>早点知道<br/>就能提前安排</div></div></Reveal><DemoLabel/></Backdrop>;
export const GlanceScene:React.FC = () => <Backdrop><Title sub="不用反复切回 Codex 查额度。">还剩多少，<br/>一眼就知道</Title><Reveal style={{position:'absolute',top:705,left:120,width:805,display:'flex',gap:80,alignItems:'center'}}><div style={{flex:1,fontSize:60,lineHeight:1.8,fontWeight:600}}><span style={{color:'#ff6570'}}>5 小时</span><br/><span style={{color:'#36d870'}}>7 天</span><div style={{fontSize:34,color:'#aebbd0',lineHeight:1.5,marginTop:22}}>两种配额<br/>放在同一个浮窗</div></div><NativeImage name="edge" style={{width:300,height:640}}/></Reveal><DemoLabel/></Backdrop>;
export const EdgeScene:React.FC = () => <Backdrop><Title sub="额度放在边上，注意力留给代码。">贴边常驻，<br/>少一点打断</Title><Reveal style={{position:'absolute',left:96,top:715,width:880,height:650,borderRadius:36,overflow:'hidden',background:'#172434',border:'2px solid #32475c'}}><div style={{padding:'28px 34px',fontSize:27,color:'#9fb1c6',borderBottom:'1px solid #32475c'}}>工作场景示意</div><div style={{margin:'54px 34px',width:420,fontSize:38,lineHeight:1.9,color:'#89a9cc'}}>专注写代码<br/><span style={{color:'#7ac6ff'}}>剩余额度</span>随手可见<br/>不用来回切窗口</div><NativeImage name="edge" style={{position:'absolute',right:0,top:109,width:220,height:470}}/></Reveal><DemoLabel/></Backdrop>;
export const DetailScene:React.FC = () => {const f=useCurrentFrame();const bubble=interpolate(f,[72,86],[0,1],{extrapolateLeft:'clamp',extrapolateRight:'clamp'});return <Backdrop><Title sub="贴边圆环和圆形气泡，可以切换。">点一下，<br/>展开配额详情</Title><Reveal style={{position:'absolute',left:85,top:725,width:910,height:650}}><NativeImage name="detail" style={{width:910,height:650,opacity:1-bubble}}/><div style={{position:'absolute',inset:0,display:'flex',gap:65,alignItems:'center',justifyContent:'center',opacity:bubble}}><NativeImage name="bubble" style={{width:240,height:240}}/><NativeImage name="bubble-detail" style={{width:540,height:650}}/></div></Reveal><DemoLabel/></Backdrop>};
export const ReminderScene:React.FC = () => <Backdrop><Title sub="额度回升，及时知道。">额度恢复，<br/>自动提醒你</Title><Reveal style={{position:'absolute',left:96,top:785,width:865}}><div style={{fontSize:68,fontWeight:600,color:'#64c1ff',marginBottom:42}}>回去继续写代码</div><div style={{fontSize:42,color:'#b6c5d9',lineHeight:1.8}}>需开启提醒，并保持应用运行。<br/>刷新只读取用量数据，<br/>不消耗模型额度。</div><div style={{marginTop:72,fontSize:32,color:'#8eabc7'}}>提醒遵循 macOS 通知设置。</div></Reveal></Backdrop>;
export const DownloadScene:React.FC = () => <Backdrop><Title sub="给常用 Codex 的你。">让额度可见，<br/>让节奏可控</Title><Reveal style={{position:'absolute',top:700,width:'100%',textAlign:'center'}}><NativeImage name="app-icon" style={{width:270,height:270}}/><div style={{fontSize:80,fontWeight:700,marginTop:14}}>ReadyCheck</div><div style={{fontSize:42,color:'#a9bfd8',marginTop:26}}>macOS · 已开源</div><div style={{fontSize:48,fontWeight:600,color:'#78c8ff',marginTop:65}}>GitHub 搜索 ReadyCheck</div><div style={{fontSize:34,color:'#b6c5d9',marginTop:24}}>github.com/whnnick/readycheck</div></Reveal></Backdrop>;
export const ReadyCheckXhsCover:React.FC = () => <Backdrop><div style={{position:'absolute',left:90,top:320,fontSize:108,fontWeight:700,lineHeight:1.15,letterSpacing:-4}}>Codex 额度<br/><span style={{color:'#78c8ff'}}>一眼就知道</span></div><NativeImage name="edge" style={{position:'absolute',top:650,right:100,width:270,height:578}}/><div style={{position:'absolute',left:100,top:760,width:500,fontSize:49,fontWeight:600,lineHeight:1.7}}>贴边常驻<br/>点开看详情<br/>恢复有提醒</div><div style={{position:'absolute',top:1235,left:96,fontSize:32,color:'#afc1d9'}}>ReadyCheck · GitHub 可下载</div><div style={{position:'absolute',top:1330,left:96,fontSize:25,color:'#8dabc7'}}>界面演示 · 配额为演示数据</div></Backdrop>;
